# go get -u -v github.com/go-task/task

version : 2

tasks :
    repl :
        cmds : [ " cabal v2-repl " ]
        
    build :
        cmds : [ " cabal v2-build " ]

    run :
        cmds : [ " cabal v2-run " ]

    test :
        cmds : [ " cabal v2-test --test-log=/dev/stdout " ]

    install :
        cmds : [ " cabal --overwrite-policy=always v2-install " ]

    clean :
        cmds : [ " cabal v2-clean " ]
